name: video_thumbnail_example
description: Demonstrates how to use the video_thumbnail plugin.
version: 0.1.7
publish_to: 'none'

environment:
  sdk: '>=2.16.0 <4.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  # Actualiza image_picker a una versión con null safety (0.8.x o superior)
  image_picker: ^0.8.5
  # Actualiza path_provider a una versión con null safety (2.0.x o superior)
  path_provider: ^2.1.5
  # Sigue apuntando al plugin principal, pero con la versión local
  video_thumbnail:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
